# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import numpy as np

import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
p_lst = list(range(5))
print(sys.getsizeof(p_lst))

96


In [3]:
np_lst = np.array(np.arange(5))
print(np_lst.nbytes)

np_lst_from_p_lst = np.array(p_lst)
print(np_lst_from_p_lst.nbytes)

20
20


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [8]:
np_lst = np.array(range(5, 11), dtype=float)
np_lst[[0, 2, -1]]

array([ 5.,  7., 10.])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [33]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
subsequence = np.array([-1, 0, 1, 4])

np.sum(array[subsequence])


27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [34]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [62]:
[np.mean(A[i], axis=0) for i in range(0, np.size(A, axis=0))]

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [61]:
np.std(A, axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [65]:
np.sum(A, axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [74]:
A[[0, 1]]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [73]:
A[[0, 2, -1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [83]:
# Python code
import time

start_time = time.time()

[i for i in range(1000000)]

end_time = time.time() - start_time

print(end_time)

0.07174158096313477

In [81]:
import time

start_time = time.time()

np.arange(1000000)

end_time = time.time() - start_time

print(end_time)

0.003252744674682617

### Task 6.2

In [97]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0

    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]

    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time result = unknown_signature(vector1, vector2)

result

CPU times: total: 0 ns
Wall time: 0 ns


32

In [114]:
vector1 = np.arange(1, 4)
vector2 = np.arange(4, 7)

%time np.matmul(vector1, vector2)

CPU times: total: 0 ns
Wall time: 0 ns


32

### Task 6.3

In [123]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []

    for i in range(len(matrix1)):
        row = []

        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])

        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%time unknown_signature(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns


[[5, 12], [21, 32]]

In [124]:
# write your numpy code here and estimate the time of execution
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%time np.array([np.multiply(matrix1[0], matrix2[0]), np.multiply(matrix1[1], matrix2[1])])

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [141]:
# Python code
def unknown_signature(lst):
    total = 0

    for num in lst:
        total += num

    result = total / len(lst)

    return result

lst = [1, 2, 3, 4, 5]

%time unknown_signature(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

In [142]:
# write your numpy code here and estimate the time of execution
lst = np.arange(1, 6)

%time np.mean(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [31]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):

        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [151]:
# write your numpy code here
lst = np.arange(1, 6)
lst[lst % 2 != 0] = 0

lst

array([0, 2, 0, 4, 0])

### Task 7.2

In [152]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]

    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)

result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [162]:
# write your numpy code here
list1 = np.array([5, 2, 7, 4, 9])
list2 = np.array([3, 6, 1, 8, 10])

result = np.array([~list1, list2 & list1, list1 | list2])
result

array([[ -6,  -3,  -8,  -5, -10],
       [  1,   2,   1,   0,   8],
       [  7,   6,   7,  12,  11]])

### Task 7.3 Optional

In [163]:
# Python code
def unknown_signature(lst):
    result = []

    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)

    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)

result_python_style

[3, 13, 11, 21]

In [207]:
# write your numpy code here
my_list = np.array([6, 9, 12, 14, 17, 20])

mask = (my_list % 2 == 0) & ((my_list % 3 == 0) | (my_list > 10))
modified_nums = (my_list[mask] ^ 7) + 2

modified_nums


array([ 3, 13, 11, 21], dtype=int32)